#spring.data.mongodb.uri=mongodb://hollow:hollow@localhost:27017/salary?authSource=admin
#logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

#grpc.client.employee-client.address=static://localhost:9092
#grpc.client.employee-client.negotiation-type=plaintext

springdoc.swagger-ui.path=/swagger-ui.html
# ???ng d?n file JSON ch?a c?u hình API
springdoc.api-docs.path=/v3/api-docs


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Timeout
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# ==============================
# Server port (Spring Boot)
# ===============================
server.port=8084