spring.data.mongodb.uri=mongodb://hollow:hollow@localhost:27017/employee?authSource=admin
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

grpc.server.port=9092

springdoc.swagger-ui.path=/swagger-ui.html
# ???ng d?n file JSON ch?a c?u hình API
springdoc.api-docs.path=/v3/api-docs

# ===============================
# Server port (Spring Boot)
# ===============================
server.port=8089