spring.data.mongodb.uri=mongodb://hollow:hollow@localhost:27017/salary?authSource=admin
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

#grpc.client.employee-client.address=static://localhost:9092
#grpc.client.employee-client.negotiation-type=plaintext

springdoc.swagger-ui.path=/swagger-ui.html
# ???ng d?n file JSON ch?a c?u hình API
springdoc.api-docs.path=/v3/api-docs

# ==============================
# Server port (Spring Boot)
# ===============================
server.port=8081